''' 
  ghmiles generates a milestones model from the list of issues in a github
  repository. 

  :copyright: Copyright 2011 Barthelemy Dagenais
  :license: BSD, see LICENSE for details
'''
from github2.client import Github
import datetime
import StringIO
import re

MILESTONE_LABEL_V = re.compile(r'''^v\d+\.\d+$''')
'''Regex used to identify milestone labels of the form v0.1'''

MILESTONE_LABEL_NUM = re.compile(r'''^\d+\.\d+$''')
'''Regex used to identify numerical milestone labels of the form 0.1'''

SIMPLE_HTML_HEADER = '''<html>
  <head><title>{0} Roadmap</title></head>
  <body>
    <h1>{0} Roadmap</h1>
'''

SIMPLE_HTML_FOOTER = '''
  <hr/>
  <p>
  Generated by <a href="https://github.com/bartdag/ghmiles">ghmiles</a>
  at {0}.
  </p>
  </body>
</html>'''

FANCY_HTML_HEADER = '''<html>
  <head>
  <title>{0} Roadmap</title>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js"></script>
  <style>
  #doc {{
    margin:auto;
    width: 960px;
  }}

  .pb {{
    width: 480px;
  }}

  #hd, #ft {{
    height: 40px;
  }}

  #ft {{
    border-top: 1px solid #ccc;
  }}

  #hd {{
    text-align: center;
  }}
  </style>
  </head>
  <body id="doc">
    <div id="hd">
      <h1>{0} Roadmap</h1>
    </div>
    <div id="main">
'''

FANCY_HTML_FOOTER = '''
    </div>
    <div id="ft">
    Generated by <a href="https://github.com/bartdag/ghmiles">ghmiles</a>
    at {0}.
    </div>
  </body>
</html>'''

class Milestone(object):

    def __init__(self, title, issues):
        self.title = title
        self.issues = issues
        self.total = len(issues)
        self.opened = sum((1 for issue in issues if issue.state == 'open'))
        self.closed = self.total - self.opened
        self.progress = float(self.closed) * 100.0 / float(self.total)

    def __repr__(self):
        return '<Milestone: {0}, {1} issues, {2:.2f}% completed>'.format(
                self.title, self.total, self.progress)

def label_key(label, padding=5):
    '''Returns a padded key from a label representing a milestone number.
    All parts of a label that are numbers are padded so that alphabetical
    sorting can work as expected (e.g., '2.0' < '11.0'). 

    For example, this function will return 'v00001.00022e-00123b' if label =
    'v1.22e-123b'.

    :param label: the milestone label
    :param padding: the maximum number of characters for each numeric part.
           Default=5
    :return: a key that can be used in alphabetical sorting
    '''
    key = prefix = ''
    components = []
   
    in_prefix = True
    current_number = current_suffix = ''

    for c in label:
        if not c.isdigit():
            if in_prefix:
                prefix += c
            else:
                current_suffix += c
        else:
            if in_prefix:
                in_prefix = False
            if current_suffix != '':
                components.append((current_number, current_suffix))
                current_number = current_suffix = ''
            current_number += c

    if not in_prefix and current_number != '':
        components.append((current_number, current_suffix))

    key = prefix
    for component in components:
        key += component[0].rjust(padding,'0') + component[1]

    return key

def get_milestone_labels(project, milestone_regex, reverse=True, github=None):
    if github is None:
        github = Github(requests_per_second=1)
    labels = sorted(github.issues.list_labels(project), key=label_key, reverse=reverse)
    project_labels = (label for label in labels if milestone_regex.match(label))
    return project_labels

def get_milestone(project, milestone_label, github=None):
    if github is None:
        github = Github(requests_per_second=1)
    issues = github.issues.list_by_label(project, milestone_label)
    return Milestone(milestone_label, issues)

def get_milestones(project, milestone_regex, reverse=True, as_list=False):
    '''Generates a list of milestones for a github project

    :param project: a string of the form `user/project`
    :param milestone_regex: a regular expression used to identify the labels
           representing milestones.
    :param reverse: If True (default), sort the milestones from the highest 
           number to the lowest. Oppositive if False.
    :param as_list: If True, generates a list of milestones. This is useful to
           determine the total number of milestones in advance. If False, this
           method returns a generator. Default is False.
    :return: A generator or a list of milestones. The milestones are sorted in
             inversed alphabetical order.
    '''

    github = Github(requests_per_second=1)
    labels = get_milestone_labels(project, milestone_regex, reverse, github)
    milestones = (get_milestone(project, label, github) for
        label in labels) 

    if as_list:
        milestones = list(milestones)

    return milestones

def get_milestones_from_labels(project, labels, as_list=False):
    '''Generates a list of milestones from the specified issue labels of a 
    github project. This can be used to generate a milestone model for recent
    milestones only.

    :param project: a string of the form `user/project`
    :param labels: a list of labels used to generate milestones. 
    :param as_list: If True, generates a list of milestones. This is useful to
           determine the total number of milestones in advance. If False, this
           method returns a generator. Default is False.
    :return: A generator or a list of milestones. 
    '''
    github = Github(requests_per_second=1)
    milestones = (get_milestone(project, label, github) for
        label in labels) 

    if as_list:
        milestones = list(milestones)

    return milestones


def write_simple_html_page(milestones, output):
    for milestone in milestones:
        output.write('<h2>Milestone: {0}</h2>\n'.format(milestone.title))
        output.write('<p><strong>Progress: {0}%</strong></p>'
                .format(milestone.progress))
        output.write('<p><em>Number of tickets: ')
        output.write('closed: {0} active: {1} total: {2}</em></p>\n'
                .format(milestone.closed, milestone.opened, milestone.total))
        output.write('<p>Issues:\n<ul>\n')
        for issue in sorted(milestone.issues, key=lambda item: int(item.number)):
            output.write('<li> #{0} {1} <em>{2}</em></li>\n'
                    .format(issue.number, issue.title, issue.state))
        output.write('</ul>\n</p>\n')

def get_simple_html_page(milestones, project_name = 'GitHub Project', 
        save_path=None, header=SIMPLE_HTML_HEADER, footer=SIMPLE_HTML_FOOTER):

    return_value = None

    if save_path is None:
        output = StringIO.StringIO()
    else:
        output = open(save_path, 'w')

    output.write(header.format(project_name))

    write_simple_html_page(milestones, output)

    output.write(footer.format(str(datetime.datetime.now())))

    if save_path is None:
        return_value = output.getvalue()

    output.close()

    return return_value


def write_fancy_html_page(milestones, output):
    for milestone in milestones:
        output.write('<h2>Milestone: {0}</h2>\n'.format(milestone.title))
        output.write('''
        <script>
        $(function() {{
          $("#progressbar{0}").progressbar({{value: {1} }});
          }});
        </script>
                '''.format(milestone.title,int(milestone.progress)))
        output.write('<div id="progressbar{0}"></div><strong> {1}%</strong>\n'
                .format(milestone.title, milestone.progress))
        output.write('<p><em>Number of tickets: ')
        output.write('closed: {0} active: {1} total: {2}</em></p>\n'
                .format(milestone.closed, milestone.opened, milestone.total))
        output.write('<p>Issues:\n<ul>\n')
        for issue in sorted(milestone.issues, key=lambda item: int(item.number)):
            output.write('<li> #{0} {1} <em>{2}</em></li>\n'
                    .format(issue.number, issue.title, issue.state))
        output.write('</ul>\n</p>\n')

def get_fancy_html_page(milestones, project_name = 'GitHub Project',
        save_path=None, header=FANCY_HTML_HEADER, footer=FANCY_HTML_FOOTER):

    return_value = None

    if save_path is None:
        output = StringIO.StringIO()
    else:
        output = open(save_path, 'w')

    output.write(header.format(project_name))

    write_fancy_html_page(milestones, output)

    output.write(footer.format(str(datetime.datetime.now())))

    if save_path is None:
        return_value = output.getvalue()

    output.close()

    return return_value
